### ISSUE TITLE
Iterating over stdin

### ISSUE THREAD

**Issue by jwass** [QuietMisdreavus/polyester#5]
Hello, I’m trying to use Polyester to do some processing on a large stream of data from stdin. The input order doesn’t matter and I’d like to avoid loading all of stdin up front and keeping the entire workload, so I thought I’d try to use Polyester instead of rayon.

I’m trying to implement an Iterator that holds the stdin lock rather than reacquiring it on every call to `next()`. I’m having trouble getting this to compile as Polyester requires the Iterator type to be `’static’` and `Send`. Here’s a very simplified version of what I’m trying to accomplish:

```
struct MyIter<'a> {
    input: std::io::Lines<std::io::StdinLock<'a>>,
}


impl<'a> MyIter<'a> {
    fn new(stdin: &'a std::io::Stdin) -> Self {
        MyIter { input: stdin.lock().lines() }
    }
}

impl<'a> Iterator for MyIter<'a> {
    type Item = u32;

    fn next(&mut self) -> Option<Self::Item> {
        self.input.next().map(|line| line.unwrap().parse::<u32>().unwrap())
    }
}

fn main() {
    let stdin = std::io::stdin();
    let myiter = MyIter::new(&stdin);
    let result = myiter.par_fold(0, |acc, v| acc + v, |acc, v| acc + v);

}
```

Fails to compile with:
```
error[E0599]: no method named `par_fold` found for type `MyIter<'_>` in the current scope
   --> src/main.rs:307:25
    |
307 |     let result = myiter.par_fold(0, |acc, v| acc + v, |acc, v| acc + v);
    |                         ^^^^^^^^
    |
    = note: the method `par_fold` exists but the following trait bounds were not satisfied:
            `MyIter<'_> : polyester::Polyester<_>`
            `&MyIter<'_> : polyester::Polyester<_>`
            `&mut MyIter<'_> : polyester::Polyester<_>`
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `par_fold`, perhaps you need to implement it:
            candidate #1: `polyester::Polyester`
```

I think I understand the error but haven't figured out a way around it - including trying to make all static variables. Is there a way to accomplish something like this with polyester?

**Comment by QuietMisdreavus** [comment]
I guess it's the `StdinLock` itself that's the culprit, since it has a non-`'static` lifetime right there. (It's holding onto a `MutexGuard`, so that lifetime is based on the call to `lock()`.) I don't see a way to force that lifetime to be `'static`, so that probably won't work out with Polyester as-is. I've been meaning to come back to this library anyway, so maybe i can crack #3 soon and help this issue out.

**Comment by jwass** [comment]
Thanks. I'm at least glad to know I wasn't missing something obvious :)

I first heard about Polyester from the rayon gitter channel, and given this comment (https://gitter.im/rayon-rs/Lobby?at=5a04d55497cedeb0482bc469), maybe there's a way to marry the two?

**Comment by QuietMisdreavus** [comment]
Ooh, i didn't know Niko made that comment! He hasn't approached me about it, but maybe i can ask him. I would love to bring this into a bigger synchronization library, whether rayon or crossbeam or something else.

**Comment by QuietMisdreavus** [comment]
I just pushed up a change to drop the `'static` requirement on `par_fold`. can you give it a shot and let me know if it works for you? I'll probably need to do something different to get `par_map` to work, but since you were asking about `par_fold`, this should help out.

**Comment by jwass** [comment]
Wow. Thanks! 

Unfortunately, I'm still getting the same error. I can verify that dropping the `'static` lifetime requirement works.

I think the remaining issue for that code above is that `MyIter` holds `StdinLock` which is not `Send`, and therefore `MyIter` is not `Send` and so still does not satisfy the trait bounds implemented in Polyester. Does that seem right? If so, I'm not sure how to get around it.

**Comment by QuietMisdreavus** [comment]
Ah, yeah, it looks like `StdinLock` holds a `MutexGuard`, which is never Send. You could see about forcing Send on `MyIter` by adding `unsafe impl Send for MyIter {}`, but i don't remember the specifics about why `MutexGuard` is `!Send`, so that feels a little suspect.

Otherwise, you could use a `mpsc` channel, dump the stuff from `StdinLock` into the channel, then use the receiver's `into_iter` to start an iterator for polyester. The ordering is weird there, so you may need to throw the Sender into another thread, lock stdin there, and start polyester after that thread is started. Something like this:

```rust
fn main() {
    let (sender, receiver) = std::sync::mpsc::channel();

    std::thread::spawn(move || {
        for line in std::io::stdin().lock().lines() {
            sender.send(line.unwrap().parse::<u32>().unwrap()).unwrap();
        }
    });

    let result = receiver.into_iter().par_fold(0, |acc, v| acc + v, |acc, v| acc + v);
}
```

This should work even with the version of polyester that's released on crates.io.
